#!/bin/bash

CREATION_DATE=$(stat -c %W /)
CURRENT_TIME=$(date +%s)
TIME_SINCE_CREATED=$(($CURRENT_TIME - $CREATION_DATE))
DAYS=$(($TIME_SINCE_CREATED / 86400))
HOURS=$((($TIME_SINCE_CREATED % 86400) / 3600))
MINUTES=$((($TIME_SINCE_CREATED % 3600) / 60))

echo "${DAYS}d ${HOURS}h ${MINUTES}m"

